# Definir el compilador
CXX=g++

# Opciones de compilación
CXXFLAGS=-Wall -pthread

# Bibliotecas contra las que enlazar
LIBS=-lpigpio -lrt -lrtaudio -lsndfile

# Nombre del ejecutable a generar
TARGET=main

# Lista de archivos fuente
SRCS=main.cpp RPI_ads1115.cpp AudioModule.cpp

# Generar automáticamente la lista de archivos objeto a partir de los archivos fuente
OBJS=$(SRCS:.cpp=.o)

# Regla por defecto
all: $(TARGET)

# Cómo construir el objetivo final a partir de los objetos
$(TARGET): $(OBJS)
    $(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)

# Incluye dependencias de archivos
-include $(SRCS:.cpp=.d)

# Cómo generar un archivo de dependencias para cada fuente
%.d: %.cpp
    $(CXX) $(CXXFLAGS) $< -MM -MT $(@:.d=.o) >$@

# Cómo compilar cada archivo fuente a un objeto
%.o: %.cpp
    $(CXX) $(CXXFLAGS) -c $< -o $@

# Regla para limpiar los archivos generados durante la compilación
clean:
    rm -f $(TARGET) $(OBJS) $(SRCS:.cpp=.d)

# Evitar que los nombres de las reglas sean confundidos con archivos
.PHONY: all clean
